### ISSUE TITLE
URL Regex for SemVer doesn't match suffixed version names (alpha, beta, etc.)

### ISSUE THREAD

**Issue by evelynhathaway** [FormidableLabs/runpkg#107]
Navigating to `eslint@6.0.0-rc.0` (alpha, beta, etc. as well) causes a redirect that 404s because of a duplicated version suffix.

```
# Inputed clean URL
https://runpkg.com/?eslint@6.0.0-rc.0
# Redirect with extra `-rc.0` suffix
https://runpkg.com/?eslint@6.0.0-rc.0-rc.0/lib/api.js
```

I've narrowed it down to the regex on Nav.js which will never match the suffixes, and will `history.pushState` the full version (`selectedVersion = "6.0.0-rc.0"`) concatenated with suffix again in the path (`path = "-rc.0/lib/api.js"`).

https://github.com/FormidableLabs/runpkg/blob/c8b36774ca50730a7335ff87e2c37aaf741545c9/components/Nav.js#L30-L33

Since the version doesn't seem to be validated, is it possible to reuse something similar to `index.js`'s `parseUrl()` which parses by using the path slashes?

**Comment by evelynhathaway** [comment]
I got the excitement jitters from being able to track down the cause of this issue quickly (and hopefully accurately 😅), so I'd love to contribute a PR for this if that would be helpful.

**Comment by VirtualDOMinic** [comment]
Awesome, @evelynhathaway ! Thanks for raising the issue - this is definitely something that would be good to fix, and one of a few likely oversights in the current RegExes.

I'll assume you're working on a PR at the moment, but will likely pick this up myself in the next 1-2 weeks if I don't hear anything from you :)

**Comment by VirtualDOMinic** [comment]
Can't spend much time at all looking at this today, but I don't see the duplication issue with URLs such as https://runpkg.com/?eslint@6.0.0-rc.0/lib/api.js - can you still recreate this bug?

Either way, I can see this (or something very closely related) is still an issue to be fixed, as the recursive fetching - at least - isn't handling the suffixes

**Comment by evelynhathaway** [comment]
It looks like the original reproduction involving redirection has been fixed, but it's still possible to run into the same issue after navigating to the above link and then switching to another version.

I haven't started work on a PR mostly because I wanted to see if you agree with replacing the strict regex for a parser or regex that mainly utilizes the URL path.

**Comment by VirtualDOMinic** [comment]
Ahh, understood! Thanks for helping me reproduce the current bug, too.

I'd be happy with any solution that is: 

- robust/doesn't cause any regressions 
- not unnecessarily complex
- efficient/not particularly inefficient

Beyond that, do whatever you see fit (I think both suggestions would match the above criteria) :).

**Comment by evelynhathaway** [comment]
Awesome! I made a pull request with the fix and a test.
