### ISSUE TITLE
Support `www` prefixed urls

### ISSUE THREAD

**Issue by rawrmonstar** [FormidableLabs/runpkg#110]
`unpkg` works both with _and_ without a `www` prefix:

- https://unpkg.com/cxs@6.2.0/
- https://www.unpkg.com/cxs@6.2.0/

but `runpkg` only resolves using the unprefixed url:

- https://runpkg.com/cxs@6.2.0/ 
- https://www.runpkg.com/cxs@6.2.0/ **(broken)**

I noticed because I was viewing https://www.unpkg.com/cxs@6.2.0/ and tried to pull it up in `runpkg` which 404s:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/13814048/59545889-40a3c480-8eda-11e9-8f1e-6a05511009a7.png">

**Comment by kiraarghy** [comment]
Hey @rawrmonstar thanks for highlighting this, I'm having a look into this now.

I think it should be a simple now.json fix!

**Comment by kiraarghy** [comment]
This is fixed with #113 !
