### ISSUE TITLE
Performance macro-issue.

### ISSUE THREAD

**Issue by kiraarghy** [FormidableLabs/runpkg#112]
We know that runpkg could be significantly more performant in some respects. 

We are creating this issue to highlight and collect up those issues!

**Comment by kiraarghy** [comment]
Known: That anchor-appending of import/ export/ require links is blocked by recursive dependency fetch.

Potential solution: Do separate initial fetch of immediate dependencies then feed into ancho-appender.

**Comment by lukejacksonn** [comment]
One thing I have noticed is that although our new dependency resolution algorithm is now more _correct_ it is much slower than it used to be (I think this is a result of more serial resolution, before it was more parallelised which did over fetch but was non-blocking and so faster).

**Comment by lukejacksonn** [comment]
Closing here as we have taken steps to drastically improve perf here https://github.com/FormidableLabs/runpkg/pull/139. Feel free to reopen with a more specific issue relevant to the V1 branch 👍
