### ISSUE TITLE
Loading states

### ISSUE THREAD

**Issue by alex-saunders** [FormidableLabs/runpkg#117]
We could introduce loading states, e.g. when opening a new file from the nav, clicking a dependency etc. 
At the moment, there is not much feedback on these requests and makes the site feel a little sluggish.

**Comment by lukejacksonn** [comment]
Yep I second this.. think there is also some weird stuff going on with state that causes dependencies to be refetched too. We need to look into:

- Initial landing page loading state
- Visiting a package page loading state
- Coming out of search causes dependencies to fetch or re-render

**Comment by lukejacksonn** [comment]
We fixed a lot of this in V1. We still need to look at loading states for the sidebar. Feel free to open an issue targetting that specifically or make a PR.
