### ISSUE TITLE
Pika Pack

### ISSUE THREAD

**Issue by alex-saunders** [FormidableLabs/runpkg#118]
It would be good to look into using [Pika Pack](https://www.pika.dev/blog/introducing-pika-pack/) to pull in dependencies as a production step.

**Comment by lukejacksonn** [comment]
Yep, this sounds sensible 👍 should be doable too given the few dependencies involved.

**Comment by lukejacksonn** [comment]
Going to close this as we are using import maps now. Feel free to open a PR with these changes.
