### ISSUE TITLE
Migrate away from SailCI

### ISSUE THREAD

**Issue by alex-saunders** [FormidableLabs/runpkg#121]
With SailCI [shutting down](https://sail.ci/blog/shutting-down) we should move to a different CI service (possibly Github actions)

**Comment by kiraarghy** [comment]
@alex-saunders happy to pair with you after work on this!

**Comment by lukejacksonn** [comment]
What is the status on this at the moment?

**Comment by kiraarghy** [comment]
@lukejacksonn I have a pr in WIP: https://github.com/FormidableLabs/runpkg/pull/133

When the testing for parseUrl branch goes in, I should be able to merge this!
