### ISSUE TITLE
Now complaining about lack of build property within scripts.

### ISSUE THREAD

**Issue by kiraarghy** [FormidableLabs/runpkg#123]
Get this error when creating PRs https://github.com/FormidableLabs/runpkg/pull/122#commitcomment-35099629.

Obviously we're doing a non-build approach with RunPkg, so this is incorrect. 

Find a way to solve this.

**Comment by alex-saunders** [comment]
I've noticed this in PRs as well but going to leave looking at it for a couple days as we're currently discussing moving runpkg over to netlify (for the analytics + functions capabilities) so not worth solving a zeit-specific problem right now.

**Comment by kiraarghy** [comment]
A fair.
