### ISSUE TITLE
More reliable package versions grabbing

### ISSUE THREAD

**Issue by alex-saunders** [FormidableLabs/runpkg#126]
Currently, the list of available package versions [is grabbed from the raw HTML](https://github.com/FormidableLabs/runpkg/blob/master/index.js#L149-L167) of the relevant unpkg page. This is a pretty brittle solution and uses some very specific heuristics to extract the correct data, meaning we're at the will of unpkg's development to maintain this solution. 
Thanks to @ryan-roemer , who found https://registry.npmjs.cf, a CORS-free NPM registry mirror. We can use this to grab the versions from a reliable API on the frontend. This should be a much more resilient & maintainable solution.

**Comment by kiraarghy** [comment]
This would be pretty cool, I'm not sure if it's possible to get the versions from the current NPM API, it at least doesn't seem to be documented?

**Comment by lukejacksonn** [comment]
This would certainly be nice to have and I guess is a quick fix if https://registry.npmjs.cf turns out to be reliable enough :shipit:

**Comment by ryan-roemer** [comment]
The cloudflare mirror has been around for years, maintains a GH repo and responds to issues, and is mentioned by npm itself in a blog post.  Is there a specific concern that we have?

If I remember correctly, there’s also other mirrors at the registry that we could further investigated for a worried, and potentially provide coded back ups as long as they also solve the CORS issue

**Comment by ryan-roemer** [comment]
https://semver.npmjs.com/ went through this issue as well depending on a third party CORS proxy, then someone suggested `registry.npmjs.cf` and then they instead decided to host one themselves. We might even be able to use that (the URL hasn't changed in three years).

The npm-provided CORS proxy is hard-coded in their GH repo at: https://github.com/npm/semver.npmjs.com/blob/master/src/entry.js#L7

```js
var REGISTRY_CORS_PROXY = 'https://cors-proxy-ee2bb0df.internal.npmjs.com';
```

**Comment by lukejacksonn** [comment]
Nice one. No I didn't have any specific concern, this will certainly be an improvement on the current implementation!
