### ISSUE TITLE
Add Netlify badge

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/runpkg#141]
To the `runpkg.com` homepage. Anywhere we'd like where it makes sense, and any one of these: https://www.netlify.com/press/#badges

**Comment by VirtualDOMinic** [comment]
@ryan-roemer see PR #177 - I'm holding off on merging for now, as I think @lukejacksonn would prefer more clarity on the reasoning behind including this badge on the runpkg homepage

**Comment by lukejacksonn** [comment]
Yeh, I can't remember why we were adding it 🤔 and generally my ethos is if it isn't useful or beautiful then you don't need it!
