### ISSUE TITLE
Confusing name

### ISSUE THREAD

**Issue by datenreisender** [FormidableLabs/runpkg#173]
What is the rationale behind the name “runpkg”? I expected something to execute/run packages but it obviously is something to browse them.

**Comment by VirtualDOMinic** [comment]
The primary reasons behind the name `runpkg` are:

- A nod to `unpkg`, which `runpkg` uses 
- An easy way for users to go from a URL on `unpkg` to the formatted, informative and easily-browsable equivalent on `runpkg`: with the name we've chosen, a user can get to the equivalent page by prepending an `r` to the `unpkg` URL
