### ISSUE TITLE
Document folder size

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/runpkg#188]
## About

Hey there! It would be awesome if the tree view showed cumulative folder size rather than number of child files/directories.

### Before
<img width="341" alt="Screenshot 2020-05-19 at 11 54 17" src="https://user-images.githubusercontent.com/10779424/82318313-8c52ce00-99c7-11ea-9b64-9abb907aafa3.png">

### After
<img width="338" alt="Screenshot 2020-05-19 at 11 54 43" src="https://user-images.githubusercontent.com/10779424/82318333-94ab0900-99c7-11ea-87e9-b272886706e1.png">

**Comment by lukejacksonn** [comment]
This would be nice! Shouldn't be too hard to implement. If anyone wants to take a stab at it then I'm happy to review 👀

**Comment by binoy14** [comment]
@lukejacksonn I have created a PR for this, if you have a chance to take a look at it.
