### ISSUE TITLE
Add a "not found" state to the app

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/runpkg#190]
## About

It would be cool if there was an indication to the user when a package couldn't be found/fetched

[Here's an example - https://www.runpkg.com/?preacct](https://www.runpkg.com/?preacct) of what currently happens

**Comment by at-syot** [comment]
Hello.
Now it's a grey background page, so the help you need are designing or coding ?

**Comment by andyrichardson** [comment]
Hey @at-syot - if you're interested in doing either, I'm sure one of the collaborators would be happy to collaborate with you!

**Comment by at-syot** [comment]
Yep, i interested. I want detail for the issue.

**Comment by Zerelt** [comment]
Saw this issue and that there haven't been replies for about a week so I thought I'd give it a try :) .

**Comment by andyrichardson** [comment]
Completed in #192
