### ISSUE TITLE
runpkg.com appears to be broken

### ISSUE THREAD

**Issue by jorroll** [FormidableLabs/runpkg#213]
I recently had occasion to access `runpkg.com` from a new Google Chrome profile and found that the site doesn't load. Inspecting the console I see the following errors:

<img width="790" alt="Screenshot 2023-06-14 at 5 58 56 PM" src="https://github.com/FormidableLabs/runpkg/assets/12599934/f9556dab-e3be-4e34-b6c0-8684767ef86d">

The response from unpkg.com is that the requested package does not contain an ES module.

```
Package react@18.2.0 does not contain an ES module
```

runpkg.com still works from my main Google Chrome profile on my computer, and I assume that's because runpkg installs and serves its static content from a service worker so it hasn't had occasion to request any files from unpkg.com recently. 

Is anyone else seeing this behavior? **An easy way to test is to try and load runpkg.com inside an incognito / private browsing window.**

**Comment by popuguytheparrot** [comment]
@lukejacksonn

**Comment by ryan-roemer** [comment]
Confirmed. We probably need an extra pinning shim entry here: https://github.com/FormidableLabs/runpkg/blob/master/index.html#L23C2-L26

But as the issue as something _else_ is now upgrading via an `unpkg.com` dep, we probably should look to:
1. Overhauling all the deps
2. Doing a real `importmap` (native not shimmed)
3. Switch to `esm.sh` which keeps react up to date (so we can use a modern one)

... etc.
