### ISSUE TITLE
Add file sizes to left sidebar

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/runpkg#47]

**Comment by lukejacksonn** [comment]
It dawned on me that we have quite a _lot_ of duplication on the average screen:

![image](https://user-images.githubusercontent.com/1457604/68484337-fc241700-0234-11ea-869c-f3e16b5bd5b4.png)

Here we essentially have the same data (dependency listings) featuring three times in different contexts! I feel like perhaps we could consolidate and de dupe by adding file sizes inline next to the links in the code or to the package directory listing as Jani suggests here.

**Comment by lukejacksonn** [comment]
This is fixed as part of https://github.com/FormidableLabs/runpkg/pull/139 👍
