### ISSUE TITLE
Same dependency fetched multiple times

### ISSUE THREAD

**Issue by bmathews** [FormidableLabs/runpkg#60]
Noticed the same dependency (last.js in this case) being fetched multiple times when initially loading lodash-es: https://runpkg.com/?lodash-es@4.17.11/lodash.js

![image](https://user-images.githubusercontent.com/848347/57588570-19b53580-74cb-11e9-9a30-9fb39ca42f5e.png)

**Comment by kiraarghy** [comment]
The PR in the review gets the number of requests for lodash.js from about 1285 to ~690 🥳
