### ISSUE TITLE
More robust file path resolution to avoid 404s etc

### ISSUE THREAD

**Issue by VirtualDOMinic** [FormidableLabs/runpkg#64]
Copying note I made in a recent PR:

> ![image](https://user-images.githubusercontent.com/19417581/57588140-0a081200-7508-11e9-898f-3e234b918268.png)
> 
> Still some mis-generated URLs. Example above is for loading webpack:
> 
> - Sometimes still assuming `/name` = `name.js` when it can be `/name/index.js`, e.g. the 404 for `/lib/compile.js` that should be for `/lib/compile/index.js`
> - Lots of files being mistaken for folders in the `tapable` package E.g. `/lib/AsyncSeriesHook/HookCodeFactory.js` should actually be `/lib/HookCodeFactory.js`

Might try to have a go at fixing this using the listing of all file and directory paths from the package `/?meta` json: could compare the path we're trying to resolve with the list of the actual file paths in the `meta`.

**Comment by lukejacksonn** [comment]
Done as part of https://github.com/FormidableLabs/runpkg/pull/139 😎
