### ISSUE TITLE
More tests to ensure new PRs cover edge cases

### ISSUE THREAD

**Issue by VirtualDOMinic** [FormidableLabs/runpkg#87]
I think we need to expand our test coverage to test new PRs against a varied range of packages/directories to ensure:

- The page doesn't crash
- The listed dependencies are what we expect
- The urls for the listed dependencies are valid/what we expect

**Comment by VirtualDOMinic** [comment]
Initial thoughts of useful things to test:

- Our fav, `lodash-es`
- `svelte` due to missing file extension in main url & use of modules, etc
- `react@16.8.6/cjs/react.production.min.js`- minified, uses a `require`, well-known file, currently crashes #78 

to be expanded...

**Comment by lukejacksonn** [comment]
All of the issues you mention here have been fixed in V1 (I think). I'm closing here due to the issue being a bit stale, but feel free to reopen with more specific bugs.
